version: '3.1'

services:
  db:
    image: postgres
    restart: always

  app:
    build: .
    restart: always
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - db
    ports:
      - 3000:3000
      - 9229:9229
